"""empty message

Revision ID: 0fa0df19381c
Revises: 
Create Date: 2019-07-04 16:26:09.650350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fa0df19381c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id')
    )
    op.create_table('data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('field_1', sa.Integer(), nullable=True),
    sa.Column('field_2', sa.Integer(), nullable=True),
    sa.Column('field_3', sa.Float(), nullable=True),
    sa.Column('field_4', sa.Integer(), nullable=True),
    sa.Column('field_5', sa.String(length=80), nullable=True),
    sa.Column('field_6', sa.Float(), nullable=True),
    sa.Column('field_7', sa.Integer(), nullable=True),
    sa.Column('field_8', sa.Integer(), nullable=True),
    sa.Column('field_9', sa.Integer(), nullable=True),
    sa.Column('field_10', sa.String(length=80), nullable=True),
    sa.Column('field_11', sa.Boolean(), nullable=True),
    sa.Column('field_12', sa.Integer(), nullable=True),
    sa.Column('field_13', sa.Float(), nullable=True),
    sa.Column('field_14', sa.Integer(), nullable=True),
    sa.Column('field_15', sa.Integer(), nullable=True),
    sa.Column('field_16', sa.Integer(), nullable=True),
    sa.Column('field_17', sa.String(length=80), nullable=True),
    sa.Column('field_18', sa.Float(), nullable=True),
    sa.Column('field_19', sa.Integer(), nullable=True),
    sa.Column('field_20', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('projects')
    # ### end Alembic commands ###
